BP_SNAPSHOTS_URI = "https://backpack.tf/api/classifieds/listings/snapshot"
TOKEN = "token"
APPID = "appid"
SKU = "sku"
TF2_APPID = 440
SCM_NAME = "SCM NAME"
SCM_PRICE = "SCM PRICE"
SCM_PROFIT = "SCM PROFIT"
AVG_SOLD = "AVG SOLD"
BP_PRICE = "BP PRICE"
KEY = "Mann Co. Supply Crate Key"
NAME = "NAME"
BACKPACK_PRICE = "BACKPACK PRICE"
LOOTFARM_PRICE = "LOOTFARM PRICE"
VALUE = "VALUE"
STOCK_TO_SELL = "STOCK TO SELL"


BP_PRICE_BUY_ORDER = "BP PRICE (BUY ORDER)"
BP_PRICE_SELL_ORDER = "BP PRICE (SELL ORDER)"
PROFIT = "PROFIT"
MARKETPLACE_PRICE = "MARKETPLACE PRICE"
BACKPACK_PRICE_BUY = "BACKPACK PRICE BUY ORDER"
BACKPACK_PRICE_SELL = "BACKPACK PRICE SELL ORDER"


NOT_CHECK_THESE_BOTS = {"76561198094818081", "76561198030343929", "76561198190592774 "} #ADD IDS OF BOTS THAT BUYS SHIT LIKE SPELLS, PAINTS AND THIS

KEY_PRICE_USD = 1.53 # PRICE YOU BUY KEYS (IT'S USED TO CALCULATE THE DIFFERENCE BETWEEN BP BUY ORDERS PRICES AND MP PRICE)
